project_name: gorels

builds:
  - id: gorels
    main: .
    binary: gorels
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      pre: wails build -clean -platform {{ .Os }}/{{ .Arch }}

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "build/bin/gorels.exe" # путь к бинарникам, которые кладёт wails build

release:
  github:
    owner: egorzhartun
    name: gorels